/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chat_sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_chat_sessions"];
        put?: never;
        post: operations["create_chat_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_chat_session"];
        put?: never;
        post?: never;
        delete: operations["delete_chat_session"];
        options?: never;
        head?: never;
        patch: operations["update_chat_session"];
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_chat_messages"];
        put?: never;
        post: operations["submit_instruction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_chat_message"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stream_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_setting"];
        put: operations["set_setting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_workspaces"];
        put?: never;
        post: operations["create_workspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_workspace"];
        put?: never;
        post?: never;
        delete: operations["delete_workspace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptedInstruction: {
            status: string;
        };
        ChatMessage: {
            content: string;
            id: string;
            role: string;
            tool_call_id?: string | null;
            tool_calls: components["schemas"]["ChatToolCall"][];
        };
        ChatSession: {
            created_at: string;
            /** @description True while this session's actor is running. Read from memory, not the database. */
            has_pending_agent: boolean;
            id: string;
            last_used_at: string;
            /**
             * @description Absent until the model names the chat session after the first turn, or a
             *     create/rename supplies one.
             */
            title?: string | null;
            updated_at: string;
            workspace_id: string;
        };
        ChatToolCall: {
            approval_status: string;
            args: unknown;
            error?: string | null;
            execution_status: string;
            id: string;
            name: string;
            result?: unknown;
        };
        CreateChatSession: {
            /**
             * @description Omitted, null, or empty leaves the chat session unnamed. The model writes a
             *     title after the first turn. Longer than
             *     [`CHAT_SESSION_TITLE_MAX_CHARS`](crate::domain::chat_session::service::CHAT_SESSION_TITLE_MAX_CHARS)
             *     is rejected.
             */
            title?: string | null;
            workspace_id: string;
        };
        CreateWorkspace: {
            /** @description Absolute or relative directory. Stored as its canonical path. */
            root: string;
        };
        SetSetting: {
            /**
             * @description When true, the value is written to the secrets file and later reads
             *     over HTTP omit it.
             */
            secret: boolean;
            value: string;
        };
        SettingResponse: {
            key: string;
            secret: boolean;
            /** @description `null` when the key is unset and has no default. Omitted when the stored value is a secret. */
            value?: string | null;
        };
        SubmitInstruction: {
            instruction: string;
        };
        UpdateChatSession: {
            title: string;
        };
        Workspace: {
            created_at: string;
            id: string;
            name: string;
            root: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_chat_sessions: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat sessions listed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"][];
                };
            };
        };
    };
    create_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatSession"];
            };
        };
        responses: {
            /** @description Chat session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
    get_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat session found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
    delete_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat session deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChatSession"];
            };
        };
        responses: {
            /** @description Chat session updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
    list_chat_messages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat messages listed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
        };
    };
    submit_instruction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitInstruction"];
            };
        };
        responses: {
            /** @description Instruction accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedInstruction"];
                };
            };
            /** @description Chat session is awaiting approval */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_chat_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
                /** @description Chat message id */
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"];
                };
            };
            /** @description Chat session or message is missing */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stream_events: {
        parameters: {
            query?: {
                /** @description Repeated. When non-empty, only these CloudEvents types are sent. */
                event_types?: string[];
                /** @description When set, only envelopes whose subject is this session. */
                session_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CloudEvents JSON as server-sent events. Each frame is `id`, `event`, and `data`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description session_id is not a UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health check */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_setting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Setting key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setting. An unset key with a default is stored, then returned. An unset key with no default has a null value. Secret values are omitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingResponse"];
                };
            };
        };
    };
    set_setting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Setting key */
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSetting"];
            };
        };
        responses: {
            /** @description Setting stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_workspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspaces listed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    create_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspace"];
            };
        };
        responses: {
            /** @description Workspace already open for this root */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Workspace created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    get_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    delete_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
