/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chat_sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_chat_sessions"];
        put?: never;
        post: operations["create_chat_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_chat_session"];
        put?: never;
        post?: never;
        delete: operations["delete_chat_session"];
        options?: never;
        head?: never;
        patch: operations["update_chat_session"];
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}/compact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["compact_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_chat_messages"];
        put?: never;
        post: operations["submit_instruction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_chat_message"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_session_review"];
        put?: never;
        post: operations["decide_session_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}/review/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_review_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stop_agent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}/tool_calls/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decide_tool_call"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}/tool_originals/{original_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_tool_original"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stream_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_setting"];
        put: operations["set_setting"];
        post?: never;
        delete: operations["delete_setting"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_workspaces"];
        put?: never;
        post: operations["create_workspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_workspace"];
        put?: never;
        post?: never;
        delete: operations["delete_workspace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_docs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/docs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_docs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/docs/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_index"];
        put: operations["put_index"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_mcp_servers"];
        put?: never;
        post: operations["focus_mcp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/mcp/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_mcp_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_skills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptedInstruction: {
            status: string;
        };
        CatalogModel: {
            /**
             * Format: int64
             * @description The model's advertised context window, in tokens.
             */
            context_window: number;
            display_name: string;
            id: string;
        };
        /**
         * @description One text file a user attached. Metadata for the `filename (1-10)` chip; the
         *     attached text is deliberately not returned.
         */
        ChatFile: {
            /** Format: int32 */
            end_line?: number | null;
            name: string;
            path?: string | null;
            /** Format: int32 */
            start_line?: number | null;
        };
        /** @description One image a user attached, referenced by id. The bytes live in the store. */
        ChatImage: {
            id: string;
            media_type: string;
        };
        ChatMessage: {
            /** @description `true` on a compaction summary. Omitted on every other message. */
            compaction?: boolean;
            content: string;
            /**
             * @description Text files the user attached. Metadata only: the attached text stays in
             *     the transcript and is not returned here, so one `GET /messages` does not
             *     carry every attachment's bytes.
             */
            files?: components["schemas"]["ChatFile"][];
            id: string;
            /**
             * @description Images the user attached. `id` is an image in the session blob file; fetch the bytes
             *     via `GET /chat_sessions/{id}/images/{image_id}`.
             */
            images?: components["schemas"]["ChatImage"][];
            role: string;
            skills?: components["schemas"]["ChatSkill"][];
            tool_call_id?: string | null;
            tool_calls: components["schemas"]["ChatToolCall"][];
            usage?: null | components["schemas"]["ChatUsage"];
        };
        ChatSession: {
            /** @description Hosts this session may fetch without another approval card. */
            allow_hosts: string[];
            created_at: string;
            /** @description True while this session's actor is running. Read from memory, not the database. */
            has_pending_agent: boolean;
            id: string;
            last_used_at: string;
            /** @description `ask`, `plan`, or `agent`. */
            mode: string;
            model_config: components["schemas"]["ModelConfigBody"];
            path_allow_read: string[];
            path_allow_write: string[];
            path_deny_read: string[];
            path_deny_write: string[];
            /**
             * @description Absent until the model names the chat session after the first turn, or a
             *     create/rename supplies one.
             */
            title?: string | null;
            /** @description Display summary of the latest turn: `idle`, `pending`, `awaiting_approval`, or `failed`. */
            turn_display: string;
            updated_at: string;
            workspace_id: string;
        };
        /** @description A skill loaded because the user wrote `@id`. */
        ChatSkill: {
            body: string;
            description: string;
            directory: string;
            files: string[];
            id: string;
        };
        /** @description The child run attached to a parent `delegate` call. */
        ChatSubagent: {
            description: string;
            mode: string;
            /**
             * Format: int64
             * @description Unix time in milliseconds when the child started.
             */
            started_ms: number;
            steps: components["schemas"]["ChatSubagentStep"][];
        };
        /** @description One child tool call shown inside a delegate card. */
        ChatSubagentStep: {
            name: string;
            status: string;
            target: string;
        };
        ChatToolCall: {
            approval_status: string;
            args: unknown;
            error?: string | null;
            execution_status: string;
            id: string;
            name: string;
            /** @description Set when compression stored the capped streams for this call. */
            original_id?: string | null;
            result?: unknown;
            subagent?: null | components["schemas"]["ChatSubagent"];
        };
        /** @description Token counts for one model turn. `input` is the prompt size, not a session total. */
        ChatUsage: {
            /** Format: int64 */
            cached: number;
            /** Format: int64 */
            input: number;
            /** Format: int64 */
            output: number;
        };
        CompactingAgent: {
            status: string;
        };
        CreateChatSession: {
            /** @description `ask`, `plan`, or `agent`. Omitted starts in agent mode. */
            mode?: string | null;
            model_config?: null | components["schemas"]["ModelConfigBody"];
            /**
             * @description Omitted, null, or empty leaves the chat session unnamed. The model writes a
             *     title after the first turn. Longer than
             *     [`CHAT_SESSION_TITLE_MAX_CHARS`](crate::domain::chat_session::service::CHAT_SESSION_TITLE_MAX_CHARS)
             *     is rejected.
             */
            title?: string | null;
            workspace_id: string;
        };
        CreateWorkspace: {
            /** @description Absolute or relative directory. Stored as its canonical path. */
            root: string;
        };
        DecideReview: {
            /** @description `approve` keeps the change. `reject` puts the baseline lines back. */
            decision: string;
            /** @description One hunk. Omitted applies `decision` to the whole file. */
            hunk_id?: string | null;
            path: string;
        };
        DecideToolCall: {
            /** @description `approve` runs the call. `reject` refuses it. */
            decision: string;
            /** @description Shown to the model when `decision` is `reject`. Omitted uses a default. */
            reason?: string | null;
        };
        DocContent: {
            content: string;
            path: string;
        };
        DocEntry: {
            /** @description Workspace-relative, `/` separated. */
            path: string;
        };
        DocSearchHit: {
            /** Format: int32 */
            end_line: number;
            /** @description Workspace-relative, `/` separated. */
            path: string;
            /**
             * Format: double
             * @description Reciprocal rank fusion score. Higher is better.
             */
            score: number;
            /** @description The chunk's opening text, cut at 500 bytes on a character boundary. */
            snippet: string;
            /** Format: int32 */
            start_line: number;
            /**
             * @description The heading chain of the section this chunk belongs to, joined by `.`
             *     (`Install.Overview`). Empty when the page did not parse into sections.
             */
            title: string;
        };
        DocSearchResult: {
            /** @description `semantic` or `ripgrep`. */
            engine: string;
            /** @description Ranked markdown hits, best first. */
            hits: components["schemas"]["DocSearchHit"][];
            /**
             * @description The index state the hits were taken from. For `semantic`, anything but
             *     `ready` means the corpus was incomplete, so the hits may be too.
             *     `ripgrep` does not start the index and does not treat this as partial.
             */
            index: components["schemas"]["IndexStatusBody"];
            /** @description The trimmed query that was run. */
            query: string;
        };
        DocsListing: {
            files: components["schemas"]["DocEntry"][];
        };
        /**
         * @description One file attachment as the client sends it. The client sends the file's raw
         *     bytes base64-encoded; the server decodes them, verifies they are text, and
         *     stores the decoded text. The server also decides whether the file is inside
         *     the workspace, from `absolute_path` — the client does not classify it.
         */
        FileAttachmentInput: {
            /**
             * @description The file's absolute path on the client, when the picker provided one
             *     (the desktop native dialog). Absent for a browser upload, which exposes
             *     only the basename. The server uses it to decide in-workspace vs outside;
             *     it is never stored and never opened.
             */
            absolute_path?: string | null;
            /** @description The file's bytes, standard base64. The server decodes and checks them. */
            content_base64: string;
            /**
             * Format: int32
             * @description 1-based last line of the slice, inclusive, when the attach was a range.
             */
            end_line?: number | null;
            /** @description Display name, e.g. `error.rs`. */
            name: string;
            /**
             * Format: int32
             * @description 1-based first line of the slice, when the attach was a range.
             */
            start_line?: number | null;
        };
        IndexCommand: {
            /** @description `paused` or `running`. */
            state: string;
        };
        IndexStatusBody: {
            error?: string | null;
            /** Format: int64 */
            files_done: number;
            /** Format: int64 */
            files_total: number;
            state: string;
        };
        /** @description The MCP JSON files for one workspace. Text is the file on disk. Secrets are not resolved. */
        McpConfig: {
            /** @description True when the stored project hash matches the file's current bytes. */
            project_enabled: boolean;
            project_path: string;
            project_text?: string | null;
            user_path: string;
            user_text?: string | null;
        };
        /** @description One MCP server this workspace is configured to use. Header and env values are omitted. */
        McpServer: {
            /** @description `https` URL or `data:image` URI from the server handshake. */
            icon?: string | null;
            id: string;
            /** @description `disconnected`, `starting`, `connected`, or `failed`. */
            status: string;
            title?: string | null;
            /** Format: int32 */
            tool_count: number;
        };
        /** @description Model and effort for one mode. Absent keys inherit the setting. */
        ModeOverrideBody: {
            model?: string | null;
            reasoning_effort?: string | null;
        };
        /**
         * @description One mode's model and effort patch.
         *
         *     `None` means the key was omitted. `Some(None)` clears it. `Some(Some)` sets it.
         */
        ModeOverridePatch: {
            /** @description Catalog model id. Null clears the session override. */
            model?: string | null;
            /** @description `low`, `medium`, or `high`. Null clears the session override. */
            reasoning_effort?: string | null;
        };
        /** @description Stored per-mode overrides. An absent mode inherits its setting. */
        ModelConfigBody: {
            agent?: components["schemas"]["ModeOverrideBody"];
            ask?: components["schemas"]["ModeOverrideBody"];
            plan?: components["schemas"]["ModeOverrideBody"];
        };
        /** @description Per-mode session overrides. An omitted mode stays as stored. */
        ModelConfigPatch: {
            agent?: null | components["schemas"]["ModeOverridePatch"];
            ask?: null | components["schemas"]["ModeOverridePatch"];
            plan?: null | components["schemas"]["ModeOverridePatch"];
        };
        ReviewFileBody: {
            /** Format: int32 */
            additions: number;
            /** @description Body before this session's first change of the path. */
            baseline: string;
            /** @description Body on disk now. Empty when the file is gone. */
            current: string;
            /** Format: int32 */
            deletions: number;
            hunks: components["schemas"]["ReviewHunkBody"][];
            lines: components["schemas"]["ReviewLineBody"][];
            path: string;
            status: components["schemas"]["ReviewStatus"];
        };
        /** @description A changed path. Bodies and lines load from `GET .../review/file`. */
        ReviewFileSummary: {
            /** Format: int32 */
            additions: number;
            /** Format: int32 */
            deletions: number;
            path: string;
            status: components["schemas"]["ReviewStatus"];
        };
        ReviewHunkBody: {
            id: string;
            /** Format: int32 */
            new_count: number;
            /**
             * Format: int32
             * @description 0-based index of the first current line.
             */
            new_start: number;
            /** Format: int32 */
            old_count: number;
            /**
             * Format: int32
             * @description 0-based index of the first baseline line.
             */
            old_start: number;
        };
        ReviewLineBody: {
            kind: components["schemas"]["ReviewLineStatus"];
            /** Format: int32 */
            new_line?: number | null;
            /** Format: int32 */
            old_line?: number | null;
            text: string;
        };
        /** @enum {string} */
        ReviewLineStatus: "context" | "delete" | "insert" | "gap";
        /** @enum {string} */
        ReviewStatus: "added" | "deleted" | "modified";
        SessionReview: {
            files: components["schemas"]["ReviewFileSummary"][];
        };
        SetSetting: {
            /**
             * @description When true, the value is written to the secrets file and later reads
             *     over HTTP omit it.
             */
            secret: boolean;
            value: string;
        };
        SettingResponse: {
            key: string;
            secret: boolean;
            /** @description `null` when the key is unset and has no default. Omitted when the stored value is a secret. */
            value?: string | null;
        };
        SkillEntry: {
            description: string;
            id: string;
            label: string;
            model_invocable: boolean;
            path: string;
            /** @description `user` or `project`. */
            scope: string;
        };
        StoppedAgent: {
            status: string;
        };
        SubmitInstruction: {
            /**
             * @description Text files the client read and is attaching. Defaulted so an older client
             *     that sends only `instruction` still parses.
             */
            files?: components["schemas"]["FileAttachmentInput"][];
            instruction: string;
        };
        ToolOriginal: {
            /** Format: int64 */
            exit_code: number;
            /** @enum {string} */
            kind: "shell";
            stderr: string;
            stdout: string;
            truncated: boolean;
        } | {
            /** @enum {string} */
            kind: "mcp";
            text: string;
            truncated: boolean;
        };
        UpdateChatSession: {
            /** @description Hostnames `web_fetch` may call without another approval. A present list replaces the stored list. */
            allow_hosts?: string[] | null;
            /** @description `ask`, `plan`, or `agent`. Omitted leaves the stored mode. */
            mode?: string | null;
            model_config?: null | components["schemas"]["ModelConfigPatch"];
            /** @description Extra read-allow regexes, appended after the built-in list. The furthest match wins; at the same end byte, more literals win. */
            path_allow_read?: string[] | null;
            /** @description Regexes. Ranked the same way as read allows. A parent match does not outrank a more specific write deny. */
            path_allow_write?: string[] | null;
            /** @description Regexes matched against the workspace-relative path. A match denies a read. */
            path_deny_read?: string[] | null;
            /** @description Regexes matched against the workspace-relative path. A match denies a write. */
            path_deny_write?: string[] | null;
            /** @description When set, replaces the title. Omitted leaves the stored title alone. */
            title?: string | null;
        };
        Workspace: {
            created_at: string;
            id: string;
            name: string;
            root: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_chat_sessions: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat sessions listed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"][];
                };
            };
        };
    };
    create_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatSession"];
            };
        };
        responses: {
            /** @description Chat session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
    get_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat session found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
    delete_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat session deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChatSession"];
            };
        };
        responses: {
            /** @description Chat session updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
    compact_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compaction accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompactingAgent"];
                };
            };
            /** @description Chat session is running, awaiting approval, or has nothing to compact */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_chat_messages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat messages listed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
        };
    };
    submit_instruction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitInstruction"];
            };
        };
        responses: {
            /** @description Instruction accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedInstruction"];
                };
            };
            /** @description Chat session is awaiting approval */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_chat_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
                /** @description Chat message id */
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"];
                };
            };
            /** @description Chat session or message is missing */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_session_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paths this session has changed, without file bodies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionReview"];
                };
            };
        };
    };
    decide_session_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideReview"];
            };
        };
        responses: {
            /** @description The file or hunk was approved or rejected */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_review_file: {
        parameters: {
            query: {
                /** @description Workspace-relative path. */
                path: string;
            };
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One changed file, with its diff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewFileBody"];
                };
            };
            /** @description That path has no remaining changes */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stop_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The actor has exited */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoppedAgent"];
                };
            };
            /** @description Chat session is missing */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    decide_tool_call: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
                /** @description Tool call id */
                call_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideToolCall"];
            };
        };
        responses: {
            /** @description Decision accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedInstruction"];
                };
            };
            /** @description Chat session is running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_tool_original: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
                /** @description Id from a ROBI_LOG header */
                original_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capped streams stored for a compressed tool result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolOriginal"];
                };
            };
            /** @description Original is missing */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stream_events: {
        parameters: {
            query?: {
                /** @description Repeated. When non-empty, only these CloudEvents types are sent. */
                event_types?: string[];
                /** @description When set, only envelopes whose subject is this session. */
                session_id?: string;
                /**
                 * @description When set without `session_id`, every session frame is delivered. Index
                 *     and MCP frames are limited to this workspace. A `session_id` query
                 *     still derives the workspace from the session row.
                 */
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CloudEvents JSON as server-sent events. Each frame is `id`, `event`, and `data`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description session_id is not a UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health check */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    list_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tool-capable models the provider can drive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogModel"][];
                };
            };
        };
    };
    list_settings: {
        parameters: {
            query: {
                /** @description Repeat to read several keys in one request. */
                key: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings in request order. An unset key with a default is stored, then returned. An unset key with no default has a null value. Secret values are omitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingResponse"][];
                };
            };
        };
    };
    get_setting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Setting key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setting. An unset key with a default is stored, then returned. An unset key with no default has a null value. Secret values are omitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingResponse"];
                };
            };
        };
    };
    set_setting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Setting key */
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSetting"];
            };
        };
        responses: {
            /** @description Setting stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_setting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Setting key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setting removed. The next read inherits. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_workspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspaces listed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    create_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspace"];
            };
        };
        responses: {
            /** @description Workspace already open for this root */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Workspace created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    get_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    delete_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_docs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Markdown files in this workspace, gitignore respected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocsListing"];
                };
            };
        };
    };
    search_docs: {
        parameters: {
            query: {
                /** @description A natural language question, or a literal string when engine is ripgrep. Required, non-blank. */
                q: string;
                /** @description How many hits to return. Default 10, maximum 20. */
                limit?: number;
                /** @description semantic (default) or ripgrep. Anything else is 400. */
                engine?: string;
            };
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked markdown hits with the engine and the index state they came from */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocSearchResult"];
                };
            };
            /** @description `q` is missing or blank, `limit` is out of range, or `engine` is unknown */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such workspace */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
                /** @description Workspace-relative path to a markdown file */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file's text */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocContent"];
                };
            };
            /** @description Not a markdown file, or not UTF-8 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such file, or a path outside the workspace */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_index: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatusBody"];
                };
            };
        };
    };
    put_index: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexCommand"];
            };
        };
        responses: {
            /** @description Index status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatusBody"];
                };
            };
            /** @description state is not paused or running */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_mcp_servers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured MCP servers and connection status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServer"][];
                };
            };
        };
    };
    focus_mcp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This workspace's MCP servers are starting; other workspaces are closed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_mcp_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MCP JSON files as stored on disk */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpConfig"];
                };
            };
        };
    };
    list_skills: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User-invocable skills */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillEntry"][];
                };
            };
        };
    };
}
