/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chat_sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_chat_sessions"];
        put?: never;
        post: operations["create_chat_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_chat_session"];
        put?: never;
        post?: never;
        delete: operations["delete_chat_session"];
        options?: never;
        head?: never;
        patch: operations["update_chat_session"];
        trace?: never;
    };
    "/api/v1/chat_sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_chat_messages"];
        put?: never;
        post: operations["submit_instruction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptedInstruction: {
            status: string;
        };
        ChatMessage: {
            content: string;
            id: string;
            role: string;
            tool_call_id?: string | null;
            tool_calls: components["schemas"]["ChatToolCall"][];
        };
        ChatSession: {
            created_at: string;
            /** @description True while this session's actor is running. Read from memory, not the database. */
            has_pending_agent: boolean;
            id: string;
            last_used_at: string;
            /**
             * @description Absent until the model names the chat session after the first turn, or a
             *     create/rename supplies one.
             */
            title?: string | null;
            updated_at: string;
            workspace_id: string;
        };
        ChatToolCall: {
            approval_status: string;
            args: unknown;
            error?: string | null;
            execution_status: string;
            id: string;
            name: string;
            result?: unknown;
        };
        CreateChatSession: {
            /**
             * @description Omitted, null, or empty leaves the chat session unnamed. The model writes a
             *     title after the first turn. Longer than
             *     [`CHAT_SESSION_TITLE_MAX_CHARS`](crate::domain::chat_session::service::CHAT_SESSION_TITLE_MAX_CHARS)
             *     is rejected.
             */
            title?: string | null;
            workspace_id: string;
        };
        SubmitInstruction: {
            instruction: string;
        };
        UpdateChatSession: {
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_chat_sessions: {
        parameters: {
            query?: {
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat sessions listed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"][];
                };
            };
        };
    };
    create_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatSession"];
            };
        };
        responses: {
            /** @description Chat session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
    get_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat session found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
    delete_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat session deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChatSession"];
            };
        };
        responses: {
            /** @description Chat session updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
    list_chat_messages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat messages listed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
        };
    };
    submit_instruction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitInstruction"];
            };
        };
        responses: {
            /** @description Instruction accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedInstruction"];
                };
            };
            /** @description Chat session is awaiting approval */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health check */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
